name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: tg推送
      run: curl "https://api.telegram.org/bot{{secrets.TG_TOKEN}}/sendMessage?chat_id={{secrets.USER_ID}}&text='【Github Actions】OpenWrt-N1打包成功'"
